import { ActionType, Category, SponsorSourceType, SponsorTime, VideoID } from "../types";
import { getFormattedTimeToSeconds } from "./formating";
import { getSkipProfileBool } from "./skipProfiles";

export function getControls(): HTMLElement {
    const controlsSelectors = [
        // Spotify
        ".bCCN4Fy0V1eENMKmu7pM",
        // Mobile Spotify
        ".s6rbLMK3UuwpqmmtNUzk"
    ];

    for (const controlsSelector of controlsSelectors) {
        const controls = Array.from(document.querySelectorAll(controlsSelector));

        if (controls.length > 0) {
            return <HTMLElement> controls[controls.length - 1];
        }
    }

    return null;
}

export function getExternalDeviceBar(): HTMLElement {
    const deviceBarSelectors = [
        // Spotify
        "div.UCkwzKM66KIIsICd6kew",
        // Mobile Spotify
        "span.weq1sklEuYjtdUrUZpYI",
        // Mobile Spotify fullscreen
        "div.twxeF9JMxAWvyaczn6eX"
    ];

    for (const deviceBarSelector of deviceBarSelectors) {
        const deviceBar = document.querySelector(deviceBarSelector);

        if (deviceBar) {
            return <HTMLElement> deviceBar;
        }
    }

    return null;
}

export function isVisible(element: HTMLElement): boolean {
    return element && element.offsetWidth > 0 && element.offsetHeight > 0;
}

export function getHashParams(): Record<string, unknown> {
    const windowHash = window.location.hash.slice(1);
    if (windowHash) {
        const params: Record<string, unknown> = windowHash.split('&').reduce((acc, param) => {
            const [key, value] = param.split('=');
            const decoded = decodeURIComponent(value);
            try {
                acc[key] = decoded?.match(/{|\[/) ? JSON.parse(decoded) : value;
            } catch (e) {
                console.error(`Failed to parse hash parameter ${key}: ${value}`);
            }

            return acc;
        }, {});

        return params;
    }

    return {};
}

export function hasAutogeneratedChapters(): boolean {
    return !!document.querySelector(".N2lUIgjp6O7qz5qe4HWm");
}

export function hasChapters(): boolean {
    return !!document.querySelector(".Uc5oEozIL6IzP0BYrjb8");
}

export function getExistingChapters(duration: number): SponsorTime[] {
    const chaptersBox = document.querySelector(".Kn1rj52CMO51rcLZ_nLt");
    
    const autogenerated = hasAutogeneratedChapters();
    if (!getSkipProfileBool("showAutogeneratedChapters") && autogenerated) return [];

    const chapters: SponsorTime[] = [];
    // .ytp-timed-markers-container indicates that key-moments are present, which should not be divided
    if (chaptersBox) {
        let lastSegment: SponsorTime = null;
        const links = chaptersBox.querySelectorAll("li");
        for (const link of links) {
            const timeElement = link.querySelector("p[data-encore-id='listRowSubtitle']") as HTMLElement;
            const description = link.querySelector("span[data-encore-id='text']") as HTMLElement;
            if (timeElement && description?.innerText?.length > 0) {
                const time = getFormattedTimeToSeconds(timeElement.innerText.replace(/\./g, ":"));
                if (time === null) return [];

                if (lastSegment) {
                    lastSegment.segment[1] = time;
                    chapters.push(lastSegment);
                }

                lastSegment = {
                    segment: [time, null],
                    category: "chapter" as Category,
                    actionType: ActionType.Chapter,
                    description: description.innerText,
                    source: autogenerated ? SponsorSourceType.Autogenerated : SponsorSourceType.Spotify,
                    UUID: null
                };
            }
        }

        if (lastSegment) {
            lastSegment.segment[1] = duration;
            chapters.push(lastSegment);
        }
    }

    return chapters;
}