name: CI

on: [push, pull_request]

jobs:

  build:
    name: Create artifacts
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkreativKout@v1
        - uses: ./.github/workreativKflows/ci/

